### ISSUE TITLE
DB接続情報を rules.yml 内に記載できるようにする

### ISSUE THREAD

**Issue by unaguna** [unaguna/validb#19]
現在はコマンド実行時の引数として接続情報を指定するが、これではすべての Rule で同じデータソースしか使用することができない。

そこで、Rule の引数としてデータソースを指定できるようにする。

```yaml
rules:
  - sql: "SELECT Code FROM country where InDepYear is NULL"
    id: "{0}"
    detection_type: "NULL_YEAR"
    msg: "null year"
    datasource: "my_datasource"
  - sql: "SELECT Code, SurfaceArea, Population FROM country where SurfaceArea < Population"
    id: "{Code}"
    level: 1
    detection_type: "TOO_SMALL"
    msg: "too small!; SurfaceArea={1}, Population={Population}"
    datasource: "my_datasource"
datasources:
  my_datasource:
    class: validb.datasources.(実装クラス名)
    url: "mysql+pymysql://?read_default_file=.my.cnf"  # ↑のコンストラクタに渡すキーワード引数
```
